name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint:all

      - name: Type-check
        run: yarn typecheck:all

      - name: Build userscript
        run: yarn userscript:release
